on:
  workflow_call:
    inputs:
      xcodeversion:
        required: true
        type: string

job:
  steps:
    Test:
      name: Testing IOS App
      runs-on: macos-13
      needs:
        - Variables
        - Localization
      steps:
        - uses: actions/checkout@master
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: ${{ inputs.xcodeversion }}
        - name: Run unit test
          run: |
            xcodebuild clean test -scheme HelloWorld -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' | xcpretty && exit ${PIPESTATUS[0]}
