#Source: https://github.com/nickwph/apple-provisioning-profile-action
name: Apple Provisioning Profile Action
description: Install a provision profile on macOS runners for Xcode development
inputs:
  PROFILE_BASE64:
    description: The Apple provisioning profile which is base64 encoded
    required: true
  PROFILE_NAME:
    description: The name provisionning profile files
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.PROFILE_BASE64 != null }}
      run: echo -n ${{ inputs.PROFILE_BASE64 }} | base64 --decode -o $RUNNER_TEMP/${{ inputs.PROFILE_NAME }}.mobileprovision
    - shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $RUNNER_TEMP/${{ inputs.PROFILE_NAME }}.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles