name: Schedule build with new features from develop

on:
  schedule:
    - cron: '0 8-18/2 * * *'
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Repository branch used (This skip the previous branch choice)
        options:
          - develop


jobs:
  check_changes:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ inputs.branch }}
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/checkout@v2
        if: ${{ inputs.branch == '' }}
        with:
          ref: develop
      - name: Check github event name
        run: echo ${{ github.event_name }}
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than 2 hours
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="2 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:
    needs:
      - check_changes
    if: ${{ needs.check_changes.outputs.should_run }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: echo "schedule activated"