name: Run release creation

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Repository branch used (This skip the previous branch choice)
        options:
          - main
      nameArtifact:
        type: string
        description: Give the artifact name
        required: true

jobs:
  Release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ inputs.branch }}
      - uses: dawidd6/action-download-artifact@v2.27.0
        id: download
        with:
          github_token: ${{ secrets.GH_PAT }}
          workflow: recette.yaml # prerelease workflow name
          workflow_conclusion: success
          name: ${{ inputs.nameArtifact }}
      - name: Remove string from name artifact
        id: reformatTagName
        run: |
          nameArtifact=${{ inputs.nameArtifact }}
          echo "NAME=release-${nameArtifact#*-}" >> $GITHUB_OUTPUT
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          custom_tag: ${{ steps.reformatTagName.outputs.name }}
          tag_prefix: "" # should have "release-" with rules and regex on artifact name
      - name: Zip the Dsym file
        run: zip -r ${{ vars.PROJECT_NAME }}.app.dSYM.zip ${{ vars.PROJECT_NAME }}.app.dSYM
      - name: check files 2
        run: ls -lla ./
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ steps.reformatTagName.outputs.name }}
          generate_release_notes: true
          token: ${{ secrets.GH_PAT }}
          name: ${{ steps.reformatTagName.outputs.name }}
          files: |
            ${{ vars.PROJECT_NAME }}.app.dSYM.zip
            ${{ vars.PROJECT_NAME }}.ipa
