name: test MacOS 13

on:
  push:
    branches:
      - develop
    schedule:
      - cron: '*/2 * * * *'

jobs:
  variables:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: get vars common variables
        id: common_vars
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: .github/workflows/config/env.test.yml
          var: test
          xcodeVersion: xcode.version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ steps.common_vars.outputs.xcodeVersion }}
      - name: check OSX version
        run: sw_vers --productVersion
      - name: show Xcode version
        run: echo xcodebuild -version #| grep "Xcode_\d{0,2}(\.\d{1,2})"
      - name: Failed switch Xcode if not equals
        if: ${{ false }} # change to ${{ xcodebuildVersion == steps.common_vars.outputs.xcodeVersion }}
        run: exit 1
      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}

  Cache:
    build:
      runs-on: macos-13
      steps:
        - uses: actions/checkout@v3
        - name: Cache Primes
          id: cache-primes
          uses: actions/cache@v3
          with:
            path: test/cache
            key: ${{ runner.os }}-primes
        - name: Generate Prime Numbers
          if: steps.cache-primes.outputs.cache-hit != 'true'
          run: /generate-primes.sh -d prime-numbers
        - name: Use Prime Numbers
          run: /primes.sh -d prime-numbers

  Certificate:
    needs:
      - variables
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install apple certificate
        run: echo "install apple certificate"
      - name: curl get provisionning
        run: curl -o ${{ runner.workspace }}/certificate https://reqbin.com/echo
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}

  Provisioning:
    needs:
      - variables
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install apple provisionning
        run: echo "install apple provisionning"
      - name: curl get provisionning
        run: curl -o ${{ runner.workspace }}/provisionning https://reqbin.com/echo
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}

  Build:
    needs:
      - Certificate
      - Provisioning
    runs-on: macos-13
    steps:
      - uses: actions/checkout@master
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: ${{ runner.workspace }}
      - name: check download artifact
        run: ls -l ${{ runner.workspace }}