name: test MacOS 13

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '4 * * * *'

jobs:
  variables:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: check OSX version
        run: sw_vers
      - name: get Xcode version
        run: echo "xcode_version=${/usr/bin/xcodebuild -version}" >> $GITHUB_ENV
      - name: show xcode version
        run: echo ${env:xcode_version:5}"
      - name: ls application xcode
        run: ls /Applications/ | grep "Xcode_"

  Certificate:
    needs:
      - variables
    runs-on: macos-13
    steps:
      - name: install apple certificate
        run: echo "install apple certificate"

  Provisionning:
    needs:
      - variables
    runs-on: macos-13
    steps:
      - name: install apple provisionning
        run: echo "install apple provisionning"