name: test MacOS 13

on:
  push:
    branches:
      - develop
    schedule:
      - cron: '*/2 * * * *'

jobs:
  Cache:
    name: Set cache
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p ${{ runner.workspace }}/cache
          echo "test" >> ${{ runner.workspace }}/cache/test.txt
      - id: cache
        uses: actions/cache/save@v3
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache

  Variables:
    name: Set variables
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Get common variables
        id: common_vars
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: .github/workflows/config/env.test.yml
          var: test
          xcodeVersion: xcode.version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ steps.common_vars.outputs.xcodeVersion }}
      - name: check OSX version
        run: sw_vers --productVersion
      - name: show Xcode version
        run: echo xcodebuild -version #| grep "Xcode_\d{0,2}(\.\d{1,2})"
      - name: Failed switch Xcode if not equals
        if: ${{ false }} # change to ${{ xcodebuildVersion == steps.common_vars.outputs.xcodeVersion }}
        run: exit 1
      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}

  Certificate:
    name: Get apple certificate
    needs:
      - variables
      - cache
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install apple certificate
        run: echo "install apple certificate"
      - uses: actions/cache/restore@v3
        id: cache-restore-certificate
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: curl get provisionning
        run: curl -o ${{ runner.workspace }}/cache/certificate.txt https://reqbin.com/echo
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}
      - id: cache
        uses: actions/cache/save@v3
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache

  Provisioning:
    name: Get apple provisioning
    needs:
      - variables
      - cache
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: install apple provisionning
        run: echo "install apple provisionning"
      - uses: actions/cache/restore@v3
        id: cache-restore-provisioning
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: curl get provisionning
        run: curl -o ${{ runner.workspace }}/cache/provisioning.txt https://reqbin.com/echo
      - uses: actions/upload-artifact@master
        with:
          name: artifact
          path: ${{ github.workspace }}
      - id: cache
        uses: actions/cache/save@v3
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}

  Build:
    name: Build IOS App
    needs:
      - Certificate
      - Provisioning
    runs-on: macos-13
    steps:
      - uses: actions/checkout@master
      - name: show permissions github workspace
        run: ls -la ${{ github.workspace }}
      - name: show permission runner workspace
        run: ls -la ${{ runner.workspace }}
      - uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: first check download artifact
        run: ls -l ${{ runner.workspace }}/cache
      - uses: actions/download-artifact@master
        with:
          name: artifact
          path: ${{ runner.workspace }}
      - name: second check download artifact
        run: ls -l ${{ runner.workspace }}