on:
  workflow_call:
    inputs:
      environment:
        required: false
        default: 'dev'
        type: string
      xcodeversion:
        required: true
        type: string
      profile_name:
        required: true
        type: string
      configuration_build:
        required: true
        type: string
      project_name:
        required: true
        type: string
      xarchivePath:
        required: true
        type: string
      plist_path:
        required: true
        type: string
      branches:
        required: false
        default: 'develop'
        type: string

    secrets:
      PROVISIONING_PROFILE:
        required: true
      CERTIFICATES_P12:
        required: true
      CERTIFICATES_P12_PASSWORD:
        required: false
      KEYCHAIN_PASSWORD:
        required: true
      GH_PAT:
        required: true
        
jobs:
  Build:
    name: Launch xcode build
    runs-on: macos-13
    outputs:
      version: ${{ steps.AppVersion.outputs.version }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ inputs.branches }}
          token: ${{ secrets.GH_PAT }}
          lfs: true
      - name: Change Xcode version
        run: |
          xcversion select ${{ inputs.xcodeversion }}
      - name: Update app version
        run: |
          xcrun agvtool new-version -all $(date +%Y%m%d%H%M%S)
      - name: Show app version
        run: |
          agvtool what-marketing-version -terse1
      - name: Set output app version
        id: AppVersion
        run: |
          echo "VERSION=$(agvtool what-marketing-version -terse1)" >> $GITHUB_OUTPUT
      - name: dump app version
        run: echo ${{ steps.AppVersion.outputs.version }}
      - name: Install the Apple provisioning profile
        uses: ./.github/actions/apple-provisionning
        with:
          PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
          PROFILE_NAME: ${{ inputs.profile_name }}
      - name: Install the Apple certificate
        uses: ./.github/actions/apple-certificate
        with:
          P12_FILE_BASE64: ${{ secrets.CERTIFICATES_P12 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Build the app
        run: xcodebuild -configuration ${{ inputs.configuration_build }} -scheme ${{ inputs.project_name }} -archivePath ${{ inputs.xarchivePath }} -sdk iphoneos archive CODE_SIGNING_ALLOWED=No CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=${{ inputs.profile_name }} | xcpretty && exit ${PIPESTATUS[0]}
      - name: Archieve the app
        run: xcodebuild -exportArchive -archivePath ${{ inputs.xarchivePath }} -exportPath ${{ inputs.configuration_build }} -exportOptionsPlist ${{ inputs.plist_path }} -allowProvisioningUpdates
      - name: Copy dSYM file
        run: |
          mv ${{ github.workspace }}/${{ inputs.xarchivePath }}/dSYMs/${{ inputs.project_name }}.app.dSYM \
          ${{ github.workspace }}/Release
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.environment }}-${{ steps.AppVersion.outputs.version }}
          path: ${{ github.workspace }}/Release
          if-no-files-found: error